import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import AuthButton from "@/components/AuthButton";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <div className="min-h-screen flex flex-col">
            <header className="border-b p-4 flex items-center justify-between">
              <div className="font-semibold">Campus Grievance Portal</div>
              <nav className="flex gap-4 text-sm items-center">
                <Link href="/">Home</Link>
                <Link href="/dashboard">Dashboard</Link>
                <Link href="/complaints/new">File Complaint</Link>
                <AuthButton />
              </nav>
            </header>
            <main className="flex-1">{children}</main>
            <footer className="border-t p-4 text-center text-xs text-gray-500">© {new Date().getFullYear()} Campus Portal</footer>
          </div>
        </Providers>
      </body>
    </html>
  );
}
